apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: yemiwebby/aks-nodejs-argocd
  newTag: ce22bfc7583072f3fc6ad026457b0ae3d3df5f57
